In [32]:
import numpy as np

class Perceptron(object):
    
    
    def __init__(self, input_size, lr = 1, epochs = 10):
        self.W = np.zeros(input_size + 1)
        self.epochs = epochs
        self.lr = lr
        
    
    def activation_fn(self, x):
        return 1 if x >= 0 else 0
    
    
    def predict(self, x):
        x = np.insert(x, 0, 1) # add "1" to first index
        z = self.W.T.dot(x) # Transpose and dot product
        a = self.activation_fn(z)
        return a
    
    
    def fit(self, X, d):
        for _ in range(self.epochs):
            for i in range(d.shape[0]):
                y = self.predict(X[i])
                e = d[i] - y
                self.W = self.W + self.lr * e * np.insert(X[i], 0, 1)

# 1. Perceptron class tanımınında varolan fonksiyonları kısaca tanıtınız.

#### init:
init fonksiyonunda Perceptron sınıfındaki Weight(W) değişkenini Perceptron objesi oluşturulurken girilen input_size adlı int parametresinin bir fazlasını alarak sıfırlardan oluşan bir numpy dizisi oluşturulur.

epochs ve lr parametreleri ise daha sonra fit işlemi yaparken yeni Weight değerlerini bulurken kullanacağımız parametrelerdir. 

epochs parametresi fit fonksiyonunda kaç iterasyon yapacağımızı belirler.

lr ise öğrenme oranını atadığımız bir parametre.

#### activation_fn:
Aktivasyon fonksiyonu, girilen x parametresi eğer 0'dan büyük veya eşitse 1, değilse 0 döndüren bir fonksiyondur. Burada girilen x parametresi, fit fonksiyonuna verilen X feature'larını kullanarak elde edilen pre-aktivasyon değeri olan z değeridir.

#### predict:
predict fonksiyonunda fit fonksiyonunda girilen X değerlerini kullanarak bir a değeri döndürülür. Bu a değerini hesaplamak için öncelikle predict fonksiyonuna girilen x parametresine(liste tipinde) algoritma gereği 0. indisinden "1" değeri eklenir. Daha sonra pre-aktivasyon değeri olan z değişkenini hesaplamak için Perceptron sınıfının Weight(W) dizisine transpose(.T) uygulayarak parametre olarak girilen x değeriyle skaler çarpımını(dot product) alırız. En son, hesaplanan z değerini aktivasyon fonksiyonuna vererek buradan dönen değeri döndürürüz.

#### fit:
fit fonksiyonu Perceptron objesini girilen X ve d parametreleriyle beraber bir öğretme yaptığımız fonksiyondur. fit fonksiyonunda Perceptron sınıfında tanımlanan epochs değişkeni ve girilen d parametresinin uzunluğunun çarpımı kadar iterasyon yapar. 

Öncelikle girilen X parametresinin i indisinde bulunan diziyi predict fonksiyonuna göndererek y değerini bulur. Bu y değerini daha sonra "e" sapmasını bulmak için, istenen çıktı olan d dizisindeki i. indisten çıkarırız. En son Perceptron sınıfının W dizisindeki ağırlığı hesaplamak için öğrenme oranı olan "lr", "e" sapması ve ilk indisine "1" değeri eklenmiş X feature'ını alıp çarparak eski W değeriyle toplarız.

# 2. XOR için verileri değiştirip çalışmasınızı gözlemleyiniz.

In [33]:
X = np.array([
        [0, 0],
        [0, 1],
        [1, 0],
        [1, 1]
    ])
d = np.array([0, 1, 1, 0])
perceptron = Perceptron(input_size=2)
print(perceptron.W)
perceptron.fit(X, d)
print(perceptron.W)

[0. 0. 0.]
[ 0. -1.  0.]


# 3. Bu class ile dersimize kayıtlı 40 öğrenci için imza tanıması yapılırsa X ve d değerleri ne olur, predict fonksiyonu nasıl kullanılır açıklayınız.

Ön edit: Öğrencilerin imzasının RGB şeklinde bulunan 3 boyutlu diziden 0 ve 1'lerden oluşan 2 boyutlu bir diziye dönüştürüldüğünü kabul ettim.

Örneğin öğrencilerin imzası 0 ve 1'lerden oluşan 200x200 matrisinde bulunan bir imza ise X değeri 40x200x200 elemanlı bir diziden oluşur. d değeri ise 40 öğrenci için 40x40'lık bir dizi olur. Bu d dizisi 0'lardan oluşan bir matris olacak fakat sadece o öğrencinin bulunduğu satır ve sütunda 1 değeri olacak. Örneğin:

                 Ayşe | Ahmet | Mehmet | ...
Ayşenin  imzası    1  |   0   |   0    | ...
Ahmetin  imzası    0  |   1   |   0    | ...
Mehmetin imzası    0  |   0   |   1    | ...
.
.
.

Girilen bu değerlerle single-layer perceptron'un bu problemi çözmek için yetersiz kaldığını düşünüyorum. Muhtemelen multi-layer perceptron bu problem için daha uygun olabilir.

# 4. Bu modelin hatası nasıl elde edilir, kendi çözümünüzü/yorumunuzu yazınız.

Single-layer perceptron'un maalesef sadece lineer olarak ayrılabilen(linearly seperable) problemleri çözmesidir. Eğer elimizdeki iki sınıf lineer olarak ayrılabilir ise demekki bu iki sınıf arasında tek bir lineer çizgi çizerek sınıflandırabiliriz. AND ve OR kapılarında bunu yapabiliyorken örneğin XOR kapısında bunu yapamıyoruz. XOR kapısını sınıflandırmak için iki ayrı çizgi çizmemiz gerekiyor. Bu yüzden XOR kapısı gibi lineer olarak ayrılamayan problemleri multi-layer perceptron ile çözebiliriz.

In [34]:
X = np.array([
        [0, 0],
        [0, 1],
        [1, 0],
        [1, 1]
    ])
d = np.array([0, 0, 0, 1])
perceptron = Perceptron(input_size=2)
print(perceptron.W)
perceptron.fit(X, d)
print(perceptron.W)

[0. 0. 0.]
[-3.  2.  1.]


In [35]:
mp = Perceptron(5)
x = np.asarray([1,2,3,4,5])
mp.predict(x)

1

In [36]:
mp.activation_fn(-10)

0

In [37]:
mp.W

array([0., 0., 0., 0., 0., 0.])